x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "12m"
    max-file: "5"

services:
  balancer:
    build: "balancer"
    image: "abrarov/haproxy-test-balancer"
    environment:
      BACKEND_HOST: "backend"
      BACKEND_PORT: "8080"
    ports:
      - "80:8080"
    logging: *default-logging

  backend:
    build: "backend"
    image: "abrarov/haproxy-test-backend"
    logging: *default-logging
