version: "2.0"

services:
  balancer:
    build: "balancer"
    image: "abrarov/haproxy-test-balancer"
    environment:
      BACKEND_HOST: "backend"
      BACKEND_PORT: "8080"
    ports:
    - "80:8080"
    logging:
      driver: "json-file"

  backend:
    build: "backend"
    image: "abrarov/haproxy-test-backend"
    logging:
      driver: "json-file"

  blackbox:
    build: "blackbox"
    image: "abrarov/haproxy-test-blackbox"
    ports:
    - "9115:9115"
    logging:
      driver: "json-file"
