{{- if .Values.backend.image.pullSecret -}}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "blackbox-test.backend.imagePullSecretName" . | quote }}
  labels:
    {{- include "blackbox-test.labels" . | nindent 4 }}
    {{- include "blackbox-test.backend.componentLabels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "blackbox-test.tplValuesRender" (dict "value" .Values.labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.backend.labels }}
    {{- include "blackbox-test.tplValuesRender" (dict "value" .Values.backend.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.annotations .Values.backend.annotations }}
  annotations:
    {{- if .Values.annotations }}
    {{- include "blackbox-test.tplValuesRender" (dict "value" .Values.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.backend.annotations }}
    {{- include "blackbox-test.tplValuesRender" (dict "value" .Values.backend.annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
type: "kubernetes.io/dockerconfigjson"
data:
  .dockerconfigjson: {{ include "blackbox-test.dockerRegistryAuthenticationConfig" (dict "imageRegistry" .Values.backend.image.registry "credentials" .Values.backend.image.pullSecret) | quote }}
{{- end }}
